on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          path: build/reports
